#!/usr/bin/env bash
# build-macos-app.sh — build Face2AI.app, the launcher described in ADR-005.
#
# The bundle is a thin AppleScript applet over scripts/face2ai-service.sh: `on run` starts the local
# process and opens the UI in the user's own browser, `on quit` stops it again. No product logic lives
# here — everything that can fail (double start, startup timeout, signal escalation) is in the shell
# script, where it is exercised from a terminal on a spare port.
#
# The applet MUST be compiled stay-open (`osacompile -s`). A one-shot applet quits as soon as `on run`
# returns, which fires `on quit` immediately and would stop the server it just started. This script
# verifies the stay-open bit rather than trusting the flag.
#
# Usage: build-macos-app.sh [destination-dir]     (default: ~/Applications)
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
SERVICE="$SCRIPT_DIR/face2ai-service.sh"
DEST_DIR="${1:-$HOME/Applications}"
APP="$DEST_DIR/Face2AI.app"
PORT="${FACE2AI_PORT:-8765}"

[ -x "$SERVICE" ] || { echo "missing or non-executable: $SERVICE" >&2; exit 1; }
command -v osacompile >/dev/null || { echo "osacompile not found — this script only builds on macOS" >&2; exit 1; }

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# The service script path is baked in at build time: the applet must keep working when Finder
# launches it with a minimal PATH and no working directory.
cat > "$WORK/launcher.applescript" <<APPLESCRIPT
-- Face2AI launcher (ADR-005). Generated by build-macos-app.sh — edit that, not this.
property serviceScript : "$SERVICE"
property uiURL : "http://127.0.0.1:$PORT"

on run
	try
		do shell script quoted form of serviceScript & " start"
		do shell script "open " & quoted form of uiURL
	on error errText
		display alert "Face2AI could not start" message errText as critical
		quit
	end try
end run

-- Stay-open applets need an idle handler; the interval is long because nothing polls here.
on idle
	return 3600
end idle

on quit
	try
		do shell script quoted form of serviceScript & " stop"
	end try
	continue quit
end quit
APPLESCRIPT

rm -rf "$APP"
mkdir -p "$DEST_DIR"
osacompile -s -o "$APP" "$WORK/launcher.applescript"

# Verify the stay-open bit rather than trusting the flag: a one-shot applet would stop the server
# the moment it finished starting it.
if /usr/libexec/PlistBuddy -c 'Print :LSUIElement' "$APP/Contents/Info.plist" >/dev/null 2>&1; then
	echo "warning: bundle is an agent (LSUIElement) — it will have no Dock icon to quit" >&2
fi
if ! grep -aq 'stay open' "$APP/Contents/Resources/Scripts/main.scpt" 2>/dev/null; then
	# The marker is not documented, so treat its absence as unproven rather than as failure.
	echo "note: could not confirm the stay-open flag from the compiled script; verify by launching it" >&2
fi

/usr/libexec/PlistBuddy -c "Set :CFBundleName Face2AI" "$APP/Contents/Info.plist" >/dev/null
/usr/libexec/PlistBuddy -c "Add :CFBundleIdentifier string ai.face2.launcher" "$APP/Contents/Info.plist" >/dev/null 2>&1 \
	|| /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier ai.face2.launcher" "$APP/Contents/Info.plist" >/dev/null
/usr/libexec/PlistBuddy -c "Add :NSHumanReadableCopyright string Local, on this Mac. No frames leave the device." "$APP/Contents/Info.plist" >/dev/null 2>&1 || true

echo "built $APP"
echo "  service: $SERVICE"
echo "  ui:      http://127.0.0.1:$PORT"
echo "Launch it from the Applications folder, or: open -a Face2AI"
