from __future__ import annotations

from typing import Protocol

from face2ai_app.domain.models import IdentityRecord


class IdentityStore(Protocol):
    def list(self) -> list[IdentityRecord]: ...
    def add(self, identity: IdentityRecord) -> IdentityRecord: ...
    def delete(self, identity_id: str) -> bool: ...
    def clear(self) -> int: ...
